version: '3.8'

services:
  postgres:
    image: postgis/postgis:15-3.3
    container_name: gps-postgres
    restart: always
    ports: [ "5432:5432" ]
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/01-init.sql
      - ./database/migration_v5.sql:/docker-entrypoint-initdb.d/02-migration_v5.sql
      - postgres_data:/var/lib/postgresql/data
    networks: [ tracking-net ]
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: gps-redis
    restart: always
    ports: [ "6379:6379" ]
    networks: [ tracking-net ]
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build: ./api
    container_name: gps-api
    restart: always
    ports: [ "3000:3000" ]
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - REDIS_HOST=redis
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks: [ tracking-net ]

  worker:
    build: ./worker
    container_name: gps-worker
    restart: always
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - REDIS_HOST=redis
      - OSRM_URL=http://osrm:5000
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      osrm:
        condition: service_started
    networks: [ tracking-net ]

  osrm:
    image: osrm/osrm-backend
    container_name: gps-osrm
    restart: always
    volumes:
      - ./osrm_data:/data
    command: |
      sh -c "if [ ! -f /data/peru-latest.osrm ]; then
        echo '[OSRM] Compilando mapa...';
        osrm-extract /data/peru-latest.osm.pbf &&
        osrm-partition /data/peru-latest.osrm &&
        osrm-customize /data/peru-latest.osrm;
      fi && osrm-routed --algorithm mld /data/peru-latest.osrm"
    networks: [ tracking-net ]

  admin-panel:
    build: ./admin-panel
    container_name: gps-admin
    restart: always
    ports: [ "80:80" ]
    networks: [ tracking-net ]

networks:
  tracking-net:
    driver: bridge

volumes:
  postgres_data:
