-- Migration v9: Add client_id for full end-to-end deduplication
-- client_id is a UUID generated by the APK per GPS point.
-- Combined with employee_id it gives a globally unique key for each point.

-- 1. Add client_id column (nullable for backwards compat with old APK versions)
ALTER TABLE locations ADD COLUMN IF NOT EXISTS client_id VARCHAR(64);

-- 2. Add columns that the worker inserts but may be missing from older schemas
ALTER TABLE locations ADD COLUMN IF NOT EXISTS source       VARCHAR(20)  DEFAULT 'gps';
ALTER TABLE locations ADD COLUMN IF NOT EXISTS quality      VARCHAR(10)  DEFAULT 'high';
ALTER TABLE locations ADD COLUMN IF NOT EXISTS confidence   FLOAT        DEFAULT 1.0;
ALTER TABLE locations ADD COLUMN IF NOT EXISTS point_type   VARCHAR(20)  DEFAULT 'normal';
ALTER TABLE locations ADD COLUMN IF NOT EXISTS battery      INTEGER;
ALTER TABLE locations ADD COLUMN IF NOT EXISTS is_charging  BOOLEAN      DEFAULT FALSE;
ALTER TABLE locations ADD COLUMN IF NOT EXISTS reset_reason VARCHAR(50);

-- 3. Unique index on (employee_id, client_id) — partial: only when client_id IS NOT NULL
--    This is the primary dedup guard for retried BullMQ jobs.
CREATE UNIQUE INDEX IF NOT EXISTS idx_locations_emp_client_id
    ON locations (employee_id, client_id)
    WHERE client_id IS NOT NULL;

-- 4. Keep existing UNIQUE(employee_id, timestamp) as secondary guard for legacy points
-- (already exists in init.sql — no action needed)

COMMENT ON COLUMN locations.client_id    IS 'UUID generated by APK per point. Used for end-to-end deduplication.';
COMMENT ON COLUMN locations.reset_reason IS 'Reason for GPS reset event (gps_off, no_fix, app_restart, etc.).';
